### ISSUE TITLE
Run stuck while preparing the simulation?

### ISSUE THREAD

**Issue by chaumanfung** [LucasJavaudin/MetropolisWebInterface#7] opened 2019-04-18 08:44 UTC
Hello,
I started this run (Brussels2, RUN6) but it got stuck:
"The server is currently preparing the simulation for the run."
I couldn't cancel the run or start a new run. 
Please advise. 
Thanks!

**Comment by LucasJavaudin** [comment] 2019-04-18 17:05
The problem is related to the MySQL database. There are about 23 millions records in the table _Matrix_ of the database (the table with the OD pairs). As a consequence, Django requires a very long time just to count the number of OD pairs with a specific origin or a specific destination when building the network output (function _get_arrivals_departures_ in `metro_app/plots.py`). I do not know if the preparation process would finish at some points but it is definitely taking too much time.

In my opinion, the only fix would be to rewrite the web interface and Metrosim so that the _Matrix_ table would be divided in multiple tables. Metrosim used to work with one _Matrix_ table for each simulation but this configuration of the database was incompatible with Django. I need to take some time to find a workaround or another fix.

In the meantime, I might try to set up a temporary workaround by creating one database for each user.

**Comment by chaumanfung** [comment] 2019-04-18 21:37
Thanks a lot for your explanation and follow-up on this. 
Just to make this clear, these records (23 million!) only have to do with the number of OD pairs, so by not importing the zero entries of population in the OD pairs, or having fewer user groups will not help the situation, right?

**Comment by LucasJavaudin** [comment] 2019-04-19 11:36
There is an entry for each OD pair of each traveler type of each simulation but only including OD pairs which where imported by the user. It does include imported OD pairs with a population of zero. Therefore, you could reduce the number of entries by not importing such OD pairs or by reducing the number of traveler types. This is not a permanent solution however because, sooner or later, the database would reach a large number of records.

**Comment by LucasJavaudin** [comment] 2019-04-29 13:41
Does the website still have trouble with imports and runs? I hope the issue is not slowing you down drastically.

I started working on a way to store the OD matrix in a tsv file on the server instead of storing them in the database. This would speed up significantly import and export of matrices. This could also slightly increase the running time of a run but this change is definitely worse it I think.

A new member will join the development team very soon so let us know if there is anything which needs to be fixed on the website!

**Comment by chaumanfung** [comment] 2019-04-29 13:55
Thanks for the follow-up. This is good news!
I still have one run (Toll schemes Brussels 2) which has been "preparing for the run" since I reported the issue... So I haven't started a new run since then. I guess if I do, they will still be stuck like this unless the issue is resolved? Or can I try one simulation with similar scale (same network) but with one traveler group only (three now)? Will it make matter worse because it will add more to the matrix?

**Comment by chaumanfung** [comment] 2019-05-02 08:51
I deleted the burdensome user groups and the zeros in the OD matrices and the runs are smooth now. So it's always good practice to drop the zeros before imports. (not sure if this "a way to store the OD matrix in a tsv file on the server instead of storing them in the database" has taken effect yet?)
Thanks again!

**Comment by LucasJavaudin** [comment] 2019-05-02 10:29
I did not change anything yet but this is great news!
We still need to keep a close eye on this issue. I think that what happened is that when you ran the large simulations, it slowed down the database which resulted in a slowing down of all simulations on the website. Now that you trimmed the size of the simulation, it can run without slowing down the website. Hence, the problem was not related to the very large number of records in the global Matrix table (there are still 24 millions records!) but to the large number of records for only one simulation.
We will update the website to prevent OD pairs with population of zero from being saved in the database.

**Comment by LucasJavaudin** [comment] 2019-05-02 14:09
I started working on replacing the Matrix table with tsv files. My work is committed to the branch [new_matrix](/LucasJavaudin/MetropolisWebInterface/tree/new_matrix). It seems to work great but the copy and deletion of simulation need to be updated and the traveler count is not working yet.
Nevertheless, it is still uncertain whether we will definitely switch to this implementation.

**Comment by chaumanfung** [comment] 2019-07-12 12:10
Update: 
Fri Jul 12 15:46:52 2019:Starting simulation process... etc 
but nothing more after the request memory line. I canceled and started another run but again nothing moves after the request memory line:
Fri Jul 12 21:58:49 2019:Starting simulation process
Fri Jul 12 21:58:49 2019:Loading database...
Fri Jul 12 21:58:55 2019:Checking volume delay functions...
Fri Jul 12 21:58:55 2019:done
Fri Jul 12 21:58:55 2019:Loading network...
Fri Jul 12 21:58:57 2019:Warning:Null free flow travel time set to 1s
Fri Jul 12 21:58:57 2019:Skipping similar messages
Fri Jul 12 21:59:05 2019:done
Fri Jul 12 21:59:05 2019:Loading demand...
Fri Jul 12 21:59:15 2019:done
Fri Jul 12 21:59:15 2019:Disaggregate demand...
Fri Jul 12 21:59:17 2019:done
Fri Jul 12 21:59:17 2019:database loaded
Fri Jul 12 21:59:17 2019:Init dynamics...
Fri Jul 12 21:59:17 2019:Warning:Request for 552 Mbytes of memory
***************************************************************************************
Hello,
I started a run around an hour ago but it is still at : ''The server is currently preparing the simulation for the run."
It looks to me that taking more than an hour to prepare for the run is not quite normal... 
I couldn't even end the run. 
I have 5 user types, >200k users in total (174, run1047).  Perhaps I should just combine the groups and try again. But before doing that I need help ending the run first.
Thanks in advance!

**Comment by chaumanfung** [comment] 2019-07-13 08:17
Ok it is not running at all since my post above. (after this:
Fri Jul 12 21:59:17 2019:Warning:Request for 552 Mbytes of memory)
What's going on?

**Comment by LucasJavaudin** [comment] 2019-07-13 12:52
The MySQL server was overloaded (again) so I restarted it. I think that your simulation is too large to be run with the current state of the server. I will discuss this issue with the Metropolis team during our next meeting. I will try to give you an update next week-end.

**Comment by LucasJavaudin** [comment] 2019-07-21 12:59
Hi Chau Man. The MySQL server is getting overloaded by delete and copy operations so we are working on improving the performance of these operations. I am still unsure whether large simulations can work smoothly when the server is not overloaded.

**Comment by LucasJavaudin** [comment] 2019-07-28 12:44
I have some good news. Commit d7547cd considerably improves the performance of delete operations. In particular, deleting zones could take a long times at it also has to delete the connected links and the OD pairs. Now, deleting all zones or the whole simulation takes less than a minute for a simulation like Paris.
The commit also reduces considerably the copying time. Sadly copying the Paris simulation still takes about half a hour. Nevertheless, I think that this update should reduce the number of stuck runs.

Another point that I have not looked into is the import of large files. These operations might also overload the Mysql server. You should at least make sure that your imports finished correctly before starting a run.

Let me know if you get another stuck run.

**Comment by LucasJavaudin** [comment] 2019-07-31 17:58
As a bonus, with commit e6f6f2d imports of network objects (zones, intersections, functions and links) should now be much faster!

**Closed as completed** 2019-07-31 17:58 UTC
